### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by vkuntz23** [stat231-f21/blog_the-hogwarts-hammers#1]
**General project topic:** 
We hope to investigate suicide rates around the world using data sets from the WHO.

**Potential questions to address:**
Does gender play a bigger role on suicide rates in different countries?
Does access to mental health facilities have an impact on suicide rates?
Does higher violence rates against women correlate with higher suicide rates in women?
Does higher violence rates against women correlate with higher suicide rates in men?

**Data sets to look at:**
https://apps.who.int/gho/data/node.main.MHSUICIDE?lang=en
Suicide rates by country and gender
https://apps.who.int/gho/data/node.main.MHFAC?lang=en
Mental health facilities by country

**Sub data sets to look potentially look for correlations in:**
https://apps.who.int/gho/data/node.main.IPV?lang=en
Violence against women by intimate partner
https://apps.who.int/gho/data/node.main.NPSV?lang=en
Violence against women by non-intimate partner

**How we will acquire the data:**
All of these data sets have CSV files we are able to download. If this doesn’t work, we can scrape it from the web.

**What we hope to deliver in our final project:** 
Create a publishable shiny app that includes the following:
We will start with several interactive maps comparing suicides and other factors
This might be too ambitious but, we could also build a projection of what suicide rates would look like in the future based on projections of these factors

**Potential schedule for blog project:**
**Status update 1 (November 9)**
Data pulled in and wrangled
Some super basic geographic plots or comparisons of factors to explore the data
**Status update 2 (November 16)**
Rough drafts of interactive maps exploring the data
**Update 3 (November 23)**
Updated plots
Potentially a draft of future projections
**Blog post (December 9)**
Final drafts of plots
Presentation

**Comment by bebailey** [comment]
Sounds like a plan!

This was not part of the requirement, but please make sure you discuss amongst yourselves exactly how you plan to divide up the work. Perhaps it would be useful to write it down as a sort of group contract, even. To the degree possible, we want equitable contributions to the core components of the blog, with flexibility for any individual to go "above and beyond" on any particular aspect of interest to them. 

---

To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

**Comment by vkuntz23** [comment]
**Status Update 1**
**What we have completed**

- Imported our data into r
- created preliminary map plots

**What we are in the process of working on**

- We have started wrangling the data but are still working on wrangling the data so that we can create the plots we want to create to answer our questions
- We have created initial plots of the data we imported but haven't created comparison plots yet

**Comment by vkuntz23** [comment]
**Status Update 2**
**What we have completed**

- Worked on making our plots interactive
- Wrangled the data 
- Created new plots to explore deeper
